In [1]:
import pandas as pd
import requests
import time
from bs4 import BeautifulSoup
from tqdm import tqdm

In [3]:
urls = {
    '19.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14060',
    '20.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14070',
    '21.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14084',
    '22.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14086',
    '23.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14087',
    '24.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14104',
    '25.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14108',
    '26.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14115',
    '27.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14125',
    '28.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14132',
    '29.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14134',
    '30.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14137',
    '31.03.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14147',
    '01.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14157',
    '02.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14160',
    '03.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14171',
    '04.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14179',
    '05.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14182',
    '06.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14185',
    '07.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14193',
    '08.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14208',
    '09.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14214',
    '10.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14219',
    '11.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14225',
    '12.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14227',
    '13.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14231',
    '14.04.2020': 'https://www.rospotrebnadzor.ru/about/info/news/news_details.php?ELEMENT_ID=14243'
}

In [3]:
len(urls)

23

In [4]:
responses = dict()
soups = dict()

In [5]:
for date, url in tqdm(urls.items()):
    response = requests.get(url)
    responses[date] = response
    time.sleep(1)
    soup = BeautifulSoup(response.text, "html.parser")
    soups[date] = soup

100%|██████████| 23/23 [00:25<00:00,  1.11s/it]

In [11]:
for date, txt in soups.items():
    with open(f'./html/{date}.txt', 'w') as f:
        f.write(txt.text)

In [1]:
import pandas as pd

# 19.03.2020

In [2]:
s = """1. Москва – 12 случаев

2. Московская область – 5 случаев

3. Свердловская область – 5 случаев

4. Тульская область – 3 случая

5. Красноярский край – 3 случая

6. Хабаровский край – 3 случая

7. Тамбовская область – 2 случая

8. Воронежская область – 2 случая

9. Краснодарский край – 2 случая

10. Кировская область – 2 случая

11. Ивановская область – 1 случай

12. Рязанская область – 1 случай

13. Мурманская область – 1 случай

14. Нижегородская область – 1 случай

15. Пермский край – 1 случай

16. Новосибирская область – 1 случай

17. Республика Саха (Якутия) – 1 случай

18. Оренбургская область – 1 случай

19. Ханты-Мансийский АО – 1 случай

20. Санкт-Петербург – 1 случай

21. Республика Чувашия – 1 случай

22. Саратовская область – 1 случай

23. Тверская область – 1 случай

"""

In [3]:
daily_data = pd.DataFrame()

In [9]:
def get_data1(s, sep='–'):
    dd = {}
    for line in s.split('\n'):
        if line != '':
            city, cases = line.split(sep)
            city = ' '.join(city.split(' ')[1:]).strip()
            cases = int(cases.strip().split(' ')[0])
            dd[city] = cases
    return dd

In [8]:
dd = get_data1(s)

In [9]:
dd

{'Москва': 12,
 'Московская область': 5,
 'Свердловская область': 5,
 'Тульская область': 3,
 'Красноярский край': 3,
 'Хабаровский край': 3,
 'Тамбовская область': 2,
 'Воронежская область': 2,
 'Краснодарский край': 2,
 'Кировская область': 2,
 'Ивановская область': 1,
 'Рязанская область': 1,
 'Мурманская область': 1,
 'Нижегородская область': 1,
 'Пермский край': 1,
 'Новосибирская область': 1,
 'Республика Саха (Якутия)': 1,
 'Оренбургская область': 1,
 'Ханты-Мансийский АО': 1,
 'Санкт-Петербург': 1,
 'Республика Чувашия': 1,
 'Саратовская область': 1,
 'Тверская область': 1}

In [10]:
daily_data = daily_data.append(dd, ignore_index=True)

# 20.03.2020

In [12]:
s = """1. Москва - 33

2. Республика Саха (Якутия) - 6

4. Самарская область - 4

5. Кировская область - 2

6. Новосибирская область - 2

7. Московская область - 1

8. Ульяновская область - 1

9. Тюменская область - 1"""

'3. Санкт-Петербург - 4'

'3. Санкт-Петербург - 4'

In [13]:
dd = get_data1(s, sep='-')

In [14]:
dd['Санкт-Петербург'] = 4

In [16]:
daily_data = daily_data.append(dd, ignore_index=True)

# 21.03.2020

In [17]:
s = """
1.Московская область $ 17
2.Москва $6
3.Республика Татарстан $5
4.Нижегородская область$ 4
5.Свердловская область$ 3
6.Тульская область $2
7.Калининградская область $2
8.Санкт-Петербург$ 2
9.Кабардино-Балкарская Республика $2
10.Краснодарский край $2
11.Рязанская область $1
12.Ставропольский край $1
13.Курганская область$ 1
14.Челябинская область$ 1
15.Ханты-Мансийский АО$ 1
16.Красноярский край $1
17.Хабаровский край $1
18.Республика Крым $1
"""

In [20]:
sep = "$"
dd = {}
for line in s.split('\n'):
    if line != '':
        city, cases = line.split(sep)
        city = city.split('.')[1].strip()
        cases = int(cases.strip().split(' ')[0])
        dd[city] = cases

In [21]:
dd

{'Московская область': 17,
 'Москва': 6,
 'Республика Татарстан': 5,
 'Нижегородская область': 4,
 'Свердловская область': 3,
 'Тульская область': 2,
 'Калининградская область': 2,
 'Санкт-Петербург': 2,
 'Кабардино-Балкарская Республика': 2,
 'Краснодарский край': 2,
 'Рязанская область': 1,
 'Ставропольский край': 1,
 'Курганская область': 1,
 'Челябинская область': 1,
 'Ханты-Мансийский АО': 1,
 'Красноярский край': 1,
 'Хабаровский край': 1,
 'Республика Крым': 1}

In [22]:
daily_data = daily_data.append(dd, ignore_index=True)

# 22.03.2020

In [23]:
s = """
Москва - 54 случая

Новгородская область - 1 случай

Кировская область - 2 случая

Архангельская область - 1 случай

Брянская область - 1 случай

Удмуртская Республика - 2 случая
"""

In [27]:
def get_data2(s, sep='-'):
    dd = {}
    for line in s.split('\n'):
        if line != '':
            city, cases = line.split(sep)
            city = city.strip()
            cases = int(cases.strip().split(' ')[0])
            dd[city] = cases
    return dd

In [28]:
dd = get_data2(s)

In [29]:
dd

{'Москва': 54,
 'Новгородская область': 1,
 'Кировская область': 2,
 'Архангельская область': 1,
 'Брянская область': 1,
 'Удмуртская Республика': 2}

In [30]:
daily_data = daily_data.append(dd, ignore_index=True)

# 23.03.2020

In [31]:
dd = {
    'Москва': 71
}

In [32]:
daily_data = daily_data.append(dd, ignore_index=True)

# 24.03.2020

In [33]:
s = """1. Москва - 28 случаев
3. Воронежская область - 4 случая
4. Свердловская область - 4 случая
5. Республика Башкортостан - 3 случая
6. Липецкая область - 2 случая
7. Орловская область - 2 случая
8. Ленинградская область - 2 случая
9. Приморский край - 2 случая
10. Калужская область - 1 случай
11. Чеченская Республика - 1 случай
12. Волгоградская область - 1 случай
13. Республика Татарстан - 1 случай
14. Самарская область - 1 случай"""

'2. Санкт-Петербург - 5 случаев'

'2. Санкт-Петербург - 5 случаев'

In [36]:
_dd = get_data2(s)
dd = {}
for key, val in _dd.items():
    k = ' '.join(key.split(' ')[1:])
    dd[k] = val
dd['Санкт-Петербург'] = 5

In [37]:
dd

{'Москва': 28,
 'Воронежская область': 4,
 'Свердловская область': 4,
 'Республика Башкортостан': 3,
 'Липецкая область': 2,
 'Орловская область': 2,
 'Ленинградская область': 2,
 'Приморский край': 2,
 'Калужская область': 1,
 'Чеченская Республика': 1,
 'Волгоградская область': 1,
 'Республика Татарстан': 1,
 'Самарская область': 1,
 'Санкт-Петербург': 5}

In [38]:
daily_data = daily_data.append(dd, ignore_index=True)

# 25.03.2020

In [39]:
s = """
1. Москва

120

2. Московская область

6

3. Республика Крым

6

4. Псковская область

4

5. Краснодарский край

4

6. Оренбургская область

3

7. Республика Саха (Якутия)

3

8. Тульская область

2

9. Республика Коми

2

10. Кабардино-Балкарская Республика

2

11. Пермский край

2

12. Брянская область

1

13. Архангельская область

1

14. Калининградская область

1

15. Ставропольский край

1

16. Ростовская область

1

17. Республика Башкортостан

1

18. Нижегородская область

1

19. Пензенская область

1

20. Челябинская область

1
"""

In [40]:
dd = {}
for line in s.split('\n'):
    if line == '':
        pass
    elif len(line) > 5:
        city = ' '.join(line.split(' ')[1:])
    elif len(line) < 5:
        num = int(line)
        dd[city] = num

In [42]:
daily_data = daily_data.append(dd, ignore_index=True)

# 26.03.2020

In [43]:
s = """
1. Москва 136

2. Свердловская область 7

3. Санкт-Петербург 5

4. Пермский край 5

5. Республика Саха (Якутия) 4

6. Ставропольский край 3

7. Республика Татарстан 3

8. Челябинская область 3

9. Красноярский край 3

10. Псковская область 2

11. Самарская область 2

12. Ханты-Мансийский АО 2

13. Республика Бурятия 2

14. Республика Хакасия 1

15. Кемеровская область 1

16. Новосибирская область 1

17. Томская область 1

18. Хабаровский край 1"""

In [44]:
dd = {}
for line in s.split('\n'):
    if line != '':
        city = ' '.join(line.split(' ')[1:-1]).strip()
        num = int(line.split(' ')[-1])
        dd[city] = num

In [46]:
daily_data = daily_data.append(dd, ignore_index=True)

# 27.03.2020

In [47]:
s = """
1. Москва

157

2. Республика Крым

7

3. Московская область

8

4. Севастополь

5

5. Волгоградская область

3

6. Чеченская Республика

2

7. Республика Мордовия

2

8. Удмуртская Республика

2

9. Самарская область

2

10. Ивановская область

1

11. Орловская область

1

12. Тульская область

1

13. Ярославская область

1

14. Республика Дагестан

1

15. Ростовская область

1

16. Республика Татарстан

1

17. Кировская область

1


"""

In [48]:
dd = {}
for line in s.split('\n'):
    if line == '':
        pass
    elif len(line) > 5:
        city = ' '.join(line.split(' ')[1:])
    elif len(line) < 5:
        num = int(line)
        dd[city] = num

In [50]:
daily_data = daily_data.append(dd, ignore_index=True)

# 28.03.2020

In [51]:
s = """
1.     Москва

114

2.     Московская область

36

3.     Санкт-Петербург

11

4.     Краснодарский край

8

5.     Республика Бурятия

6

6.     Ивановская область

5

7.     Ленинградская область

4

8.     Свердловская область

4

9.     Челябинская область

4

10.                       Красноярский край

4

11.                       Сахалинская область

4

12.                       Липецкая область

3

13.                       Тульская область

3

14.                       Калининградская область

3

15.                       Республика Татарстан

3

16.                       Нижегородская область

3

17.                       Чеченская Республика

2

18.                       Оренбургская область

2

19.                       Новосибирская область

2

20.                       Брянская область

1

21.                       Костромская область

1

22.                       Смоленская область

1

23.                       Республика Адыгея

1

24.                       Пермский край

1

25.                       Саратовская область

1

26.                       Республика Крым

1

"""

In [52]:
dd = {}
for line in s.split('\n'):
    if line == '':
        pass
    elif len(line) > 5:
        city = ' '.join(line.split(' ')[1:]).strip()
    elif len(line) < 5:
        num = int(line)
        dd[city] = num

In [54]:
daily_data = daily_data.append(dd, ignore_index=True)

# 29.03.2020

In [55]:
s = """
1. Москва 197
2. Московская область 27
3. Санкт-Петербург 5
4. Пензенская область 5
5. Республика Коми 4
6. Чеченская Республика 4
7. Челябинская область 3
8. Омская область 3
9. Ленинградская область 2
10. Мурманская область 2
11. Новгородская область 2
12. Хабаровский край 2
13. Белгородская область 1
14. Липецкая область 1
15. Рязанская область 1
16. Ярославская область 1
17. Республика Башкортостан 1
18. Республика Мордовия 1
19. Кировская область 1
20. Тюменская область 1
21. Ханты-Мансийский АО 1
22. Иркутская область 1
23. Новосибирская область 1
24. Томская область 1
25. Республика Саха (Якутия) 1
26. Амурская область 1
"""

In [108]:
def get_data3(s):
    dd = {}
    for line in s.split('\n'):
        if line != '':
            city = ' '.join(line.split(' ')[1:-1]).strip()
            num = int(line.split(' ')[-1])
            dd[city] = num
    return dd

In [57]:
dd = get_data3(s)

In [59]:
daily_data = daily_data.append(dd, ignore_index=True)

# 30.03.2020

In [60]:
s = """
1. Москва 212
2. Республика Коми 15
3. Санкт-Петербург 8
4. Московская область 7
5. Республика Бурятия 5
6. Архангельская область 4
7. Белгородская область 3
8. Псковская область 3
9. Республика Адыгея 3
10. Республика Дагестан 3
11. Кировская область 3
12. Владимирская область 2
13. Ивановская область 2
14. Рязанская область 2
15. Вологодская область 2
16. Ленинградская область 2
17. Мурманская область 2
18. Кабардино-Балкарская Республика 2
19. Республика Марий Эл 2
20. Пермский край 2
21. Саратовская область 2
22. Челябинская область 2
23. Красноярский край 2
24. Калужская область 1
25. Липецкая область 1
26. Тверская область 1
27. Тульская область 1
28. Калининградская область 1
29. Республика Калмыкия 1
30. Ставропольский край 1
31. Оренбургская область 1
32. Республика Хакасия 1
33. Алтайский край 1
34. Иркутская область 1
35. Новосибирская область 1"""

In [61]:
dd = get_data3(s)

In [63]:
daily_data = daily_data.append(dd, ignore_index=True)

# 31.03.2020

In [64]:
s ="""1. Москва 387

2. Санкт-Петербург 48

3. Республика Дагестан 9

4. Свердловская область 9

5. Мурманская область 6

6. Республика Бурятия 6

7. Республика Татарстан 5

8. Пензенская область 5

9. Ленинградская область 3

10. Ростовская область 3

11. Воронежская область 2

12. Астраханская область 2

13. Республика Башкортостан 2

14. Тюменская область 2

15. Приморский край 2

16. Костромская область 1

17. Республика Калмыкия 1

18. Нижегородская область 1

19. Самарская область 1

20. Алтайский край 1

21. Иркутская область 1

22. Хабаровский край 1

23. Магаданская область 1

24. Республика Крым 1"""

In [65]:
dd = get_data3(s)

In [67]:
daily_data = daily_data.append(dd, ignore_index=True)

# 01.04.2020

In [68]:
s = """1. Москва 267

2. Республика Коми 32

3. Санкт-Петербург 27

4. Московская область 15

5. Саратовская область 11

6. Вологодская область 7

7. Челябинская область 7

8. Ленинградская область 6

9. Республика Бурятия 6

10. Красноярский край 6

11. Тульская область 5

12. Краснодарский край 5

13. Воронежская область 4

14. Волгоградская область 4

15. Пензенская область 4

16. Омская область 4

17. Курская область 3

18. Тамбовская область 3

19. Ханты-Мансийский АО 3

20. Брянская область 2

21. Ивановская область 2

22. Республика Дагестан 2

23. Кабардино-Балкарская Республика 2

24. Республика Северная Осетия 2

25. Владимирская область 1

26. Липецкая область 1

27. Тверская область 1

28. Чеченская Республика 1

29. Республика Башкортостан 1

30. Республика Мордовия 1

31. Алтайский край 1

32. Новосибирская область 1

33. Приморский край 1

34. Хабаровский край 1

35. Сахалинская область 1"""

In [69]:
dd = get_data3(s)

In [71]:
daily_data = daily_data.append(dd, ignore_index=True)

# 02.04.2020

In [72]:
s = """
1. Москва

595

2. Московская область

43

3. Санкт-Петербург

22

4. Нижегородская область

13

5. Ленинградская область

11

6. Республика Дагестан

10

7. Калининградская область

7

8. Пермский край

7

9. Ставропольский край

5

10. Оренбургская область

5

11. Свердловская область

5

12. Республика Бурятия

5

13. Красноярский край

5

14. Липецкая область

4

15. Мурманская область

4

16. Ростовская область

4

17. Иркутская область

4

18. Вологодская область

3

19. Калужская область

2

20. Республика Коми

2

21. Республика Северная Осетия

2

22. Республика Башкортостан

2

23. Республика Марий Эл

2

24. Самарская область

2

25. Ямало-Ненецкий АО

2

26. Омская область

2

27. Белгородская область

1

28. Республика Адыгея

1

29. Алтайский край

1

"""

In [73]:
dd = {}
for line in s.split('\n'):
    if line == '':
        pass
    elif len(line) > 5:
        city = ' '.join(line.split(' ')[1:]).strip()
    elif len(line) < 5:
        num = int(line)
        dd[city] = num

In [75]:
daily_data = daily_data.append(dd, ignore_index=True)

# 03.04.2020

In [76]:
s = """1. Москва 448

2. Московская область 34

3. Краснодарский край 17

4. Пензенская область 11

5. Ленинградская область 10

6. Ямало-Ненецкий АО 10

7. Санкт-Петербург 9

8. Ханты-Мансийский АО 8

9. Республика Татарстан 6

10. Республика Калмыкия 5

11. Тюменская область 5

12. Саратовская область 4

13. Липецкая область 3

14. Астраханская область 3

15. Кировская область 3

16. Еврейская АО 3

17. Брянская область 2

18. Ивановская область 2

19. Чеченская Республика 2

20. Челябинская область 2

21. Приморский край 2

22. Республика Крым 2

23. Курская область 1

24. Рязанская область 1

25. Тверская область 1

26. Архангельская область 1

27. Республика Ингушетия 1

28. Пермский край 1

29. Свердловская область 1

30. Республика Бурятия 1

31. Иркутская область 1

32. Хабаровский край 1

"""

In [77]:
dd = get_data3(s)

In [79]:
daily_data = daily_data.append(dd, ignore_index=True)

# 04.04.2020

In [80]:
s = """
1. Москва - 434

2. Московская область - 49

4. Брянская область - 12

5. Ивановская область - 10

6. Рязанская область - 6

7. Ленинградская область - 6

8. Костромская область - 5

9. Республика Бурятия - 4

10. Орловская область - 3

11. Республика Коми - 3

12. Чеченская Республика - 3

13. Кировская область - 3

14. Челябинская область - 3

15. Алтайский край - 3

16. Амурская область - 3

17. Воронежская область - 2

18. Тульская область - 2

19. Ярославская область - 2

20. Республика Адыгея - 2

21. Белгородская область - 1

22. Калужская область - 1

23. Смоленская область - 1

24. Тамбовская область - 1

25. Вологодская область - 1

26. Республика Северная Осетия - 1

27. Республика Мордовия - 1

28. Удмуртская Республика - 1

29. Курганская область - 1

30. Свердловская область - 1

31. Омская область - 1

32. Сахалинская область - 1"""
'3. Санкт-Петербург - 15'

'3. Санкт-Петербург - 15'

In [81]:
dd_ = get_data2(s)
dd = {}
for key,val in dd_.items():
    k = ' '.join(key.split(' ')[1:]).strip()
    dd[k] = val

In [82]:
dd['Санкт-Петербург'] = 15

In [84]:
daily_data = daily_data.append(dd, ignore_index=True)

# 05.04.2020

In [85]:
s = """
1. Москва 536
2. Московская область 45
3. Нижегородская область 22
4. Санкт-Петербург 20
5. Тульская область 10
6. Ленинградская область 10
7. Красноярский край 4
8. Ханты-Мансийский АО 3
9. Республика Крым 2
10. Камчатский край 2
11. Ярославская область 1
12. Челябинская область 1
13. Хабаровский край 1
14. Новосибирская область 1
"""

In [86]:
dd = get_data3(s)

In [88]:
daily_data = daily_data.append(dd, ignore_index=True)

# 06.04.2020

In [89]:
s = """1. Москва 591
2. Московская область 82
3. Санкт-Петербург 35
4. Республика Коми 31
5. Республика Татарстан 16
6. Краснодарский край 11
7. Ивановская область 10
8. Тульская область 10
9. Вологодская область 10
10. Воронежская область 9
11. Ставропольский край 9
12. Республика Марий Эл 9
13. Нижегородская область 9
14. Липецкая область 8
15. Тамбовская область 8
16. Республика Бурятия 8
17. Волгоградская область 7
18. Архангельская область 6
19. Республика Адыгея 6
20. Брянская область 5
21. Рязанская область 5
22. Ленинградская область 5
23. Республика Дагестан 5
24. Пензенская область 5
25. Алтайский край 5
26. Белгородская область 4
27. Свердловская область 4
28. Челябинская область 4
29. Мурманская область 3
30. Республика Северная Осетия 3
31. Красноярский край 3
32. Иркутская область 3
33. Владимирская область 2
34. Тверская область 2
35. Республика Карелия 2
36. Новгородская область 2
37. Чувашская Республика 2
38. Оренбургская область 2
39. Республика Хакасия 2
40. Кемеровская область 2
41. Калужская область 1
42. Костромская область 1
43. Орловская область 1
44. Смоленская область 1
45. Псковская область 1
46. Чеченская Республика 1
47. Республика Мордовия 1
48. Ульяновская область 1
49. Республика Крым 1"""

In [90]:
dd = get_data3(s)

In [92]:
daily_data = daily_data.append(dd, ignore_index=True)

# 07.04.2020

In [93]:
s = """1. Москва - 697

2. Санкт-Петербург - 69

3. Московская область - 67

4. Брянская область - 32

5. Калининградская область - 29

6. Ставропольский край - 19

7. Пензенская область - 19

8. Ханты-Мансийский АО - 19

9. Ямало-Ненецкий АО - 18

10. Ивановская область - 14

11. Республика Дагестан - 13

12. Республика Коми - 11

13. Краснодарский край - 11

14. Волгоградская область - 11

15. Пермский край - 11

16. Тульская область - 10

17. Ростовская область - 8

18. Владимирская область - 7

19. Свердловская область - 7

20. Тюменская область - 7

21. Республика Ингушетия - 6

22. Саратовская область - 6

23. Орловская область - 5

24. Ярославская область - 5

25. Кабардино-Балкарская Республика - 5

26. Хабаровский край - 5

27. Калужская область - 4

28. Псковская область - 4

29. Республика Калмыкия - 4

30. Удмуртская Республика - 4

31. Омская область - 4

32. Белгородская область - 3

33. Карачаево-Черкесская Республика - 3

34. Чувашская Республика - 3

35. Иркутская область - 3

36. Республика Башкортостан - 2

37. Кировская область - 2

38. Ульяновская область - 2

39. Республика Северная Осетия - 1

40. Чеченская Республика - 1

41. Челябинская область - 1

42. Приморский край - 1

43. Республика Крым - 1"""

In [4]:
def get_data4(s):
    excp = ('Санкт-Петербург',
            'Ханты-Мансийский АО',
            'Ямало-Ненецкий АО',
            'Кабардино-Балкарская Республика',
           'Карачаево-Черкесская Республика')
    dd = {}
    for line in s.split('\n'):
        flag = True
        if line != '':
            for c in excp:
                if c in line:
                    city = c
                    cases = int(line.split('-')[-1].strip())
                    dd[c] = cases
                    flag = False
            if flag:
                city, cases = line.split('-')
                city = ' '.join(city.split(' ')[1:]).strip()
                cases = int(cases.strip().split(' ')[0])
                dd[city] = cases
    return dd

In [105]:
dd = get_data4(s)

In [107]:
daily_data = daily_data.append(dd, ignore_index=True)

# 08.04.2020

In [120]:
s = """

1.      Москва

660

2.      Московская область

95

3.      Санкт-Петербург

34

4.      Ленинградская область

32

5.      Республика Марий Эл

27

6.      Мурманская область

25

7.      Краснодарский край

24

8.      Нижегородская область

24

9.      Липецкая область

18

10.  Республика Коми

18

11.  Республика Ингушетия

18

12.  Рязанская область

15

13.  Ямало-Ненецкий АО

11

14.  Воронежская область

10

15.  Кабардино-Балкарская Республика

10

16.  Чувашская Республика

9

17.  Оренбургская область

8

18.  Хабаровский край

8

19.  Республика Мордовия

7

20.  Республика Бурятия

7

21.  Красноярский край

7

22.  Приморский край

7

23.  Курская область

6

24.  Тамбовская область

6

25.  Республика Северная Осетия

6

26.  Алтайский край

6

27.  Тульская область

5

28.  Чеченская Республика

5

29.  Свердловская область

5

30.  Сахалинская область

5

31.  Белгородская область

4

32.  Смоленская область

4

33.  Тверская область

4

34.  Вологодская область

4

35.  Республика Калмыкия

4

36.  Ростовская область

4

37.  Республика Башкортостан

4

38.  Ханты-Мансийский АО

3

39.  Забайкальский край

3

40.  Еврейская АО

3

41.  Владимирская область

2

42.  Карачаево-Черкесская Республика

2

43.  Кемеровская область

2

44.  Новосибирская область

2

45.  Брянская область

1

46.  Калининградская область

1

47.  Республика Дагестан

1

48.  Пензенская область

1

49.  Самарская область

1

50.  Саратовская область

1

51.  Курганская область

1

52.  Республика Хакасия

1

53.  Омская область

1

54.  Томская область

1

55.  Республика Саха (Якутия)

1

56.  Республика Крым

1"""

In [121]:
dd = {}
for line in s.split('\n'):
    if line == '':
        pass
    elif len(line) > 5:
        city = ' '.join(line.split(' ')[1:]).strip()
    elif len(line) < 5:
        num = int(line)
        dd[city] = num

In [122]:
daily_data = daily_data.append(dd, ignore_index=True)

# 09.04.2020

In [123]:
s = """1. Москва – 857

2. Московская область – 199

3. Санкт-Петербург – 44

4. Брянская область – 40

5. Республика Коми – 31

6. Владимирская область – 24

7. Краснодарский край – 20

8. Ленинградская область – 18

9. Астраханская область – 16

10. Ивановская область – 13

11. Республика Дагестан – 13

12. Тульская область – 12

13. Курская область – 10

14. Архангельская область – 10

15. Республика Татарстан – 9

16. Пермский край – 9

17. Вологодская область – 8

18. Республика Калмыкия – 8

19. Кировская область – 8

20. Тверская область – 7

21. Новгородская область – 7

22. Республика Северная Осетия – 7

23. Нижегородская область – 7

24. Республика Башкортостан – 6

25. Орловская область – 5

26. Новосибирская область – 5

27. Приморский край – 5

28. Липецкая область – 4

29. Смоленская область – 4

30. Республика Мордовия – 4

31. Саратовская область – 4

32. Республика Бурятия – 4

33. Костромская область – 3

34. Калининградская область – 3

35. Ставропольский край – 3

36. Ростовская область – 3

37. Свердловская область – 3

38. Алтайский край – 3

39. Иркутская область – 3

40. Камчатский край – 3

41. Республика Крым – 3

42. Ярославская область – 2

43. Псковская область – 2

44. Чувашская Республика – 2

45. Ульяновская область – 2

46. Челябинская область – 2

47. Мурманская область – 1

48. Карачаево-Черкесская Республика – 1

49. Республика Марий Эл – 1

50. Тюменская область – 1"""

In [124]:
dd = get_data1(s)

In [126]:
daily_data = daily_data.append(dd, ignore_index=True)

# 10.04.2020

In [127]:
s = """1. Москва 1124
2. Московская область 182
3. Республика Коми 58
4. Санкт-Петербург 35
5. Ульяновская область 34
6. Нижегородская область 32
7. Мурманская область 23
8. Республика Марий Эл 22
9. Краснодарский край 20
10. Республика Башкортостан 18
11. Ленинградская область 17
12. Чувашская Республика 15
13. Пензенская область 15
14. Тамбовская область 12
15. Калининградская область 10
16. Ставропольский край 10
17. Белгородская область 8
18. Калужская область 7
19. Липецкая область 7
20. Орловская область 7
21. Республика Адыгея 7
22. Рязанская область 6
23. Новгородская область 6
24. Республика Бурятия 6
25. Республика Тыва 6
26. Тверская область 5
27. Тульская область 5
28. Республика Северная Осетия 5
29. Ростовская область 5
30. Владимирская область 4
31. Воронежская область 4
32. Республика Ингушетия 4
33. Кабардино-Балкарская Республика 4
34. Пермский край 4
35. Саратовская область 4
36. Иркутская область 4
37. Кемеровская область 4
38. Хабаровский край 4
39. Костромская область 3
40. Вологодская область 3
41. Карачаево-Черкесская Республика 3
42. Оренбургская область 3
43. Тюменская область 3
44. Республика Хакасия 3
45. Новосибирская область 3
46. Республика Крым 3
47. Смоленская область 2
48. Волгоградская область 2
49. Республика Мордовия 2
50. Удмуртская Республика 2
51. Самарская область 2
52. Свердловская область 2
53. Омская область 2
54. Еврейская АО 2
55. Курская область 1
56. Республика Дагестан 1
57. Кировская область 1
"""

In [128]:
dd = get_data3(s)

In [130]:
daily_data = daily_data.append(dd, ignore_index=True)

# 11.04.2020

In [135]:
s = """
1. Москва

1030

2. Московская область

152

3. Санкт-Петербург

80

4. Нижегородская область

33

5. Брянская область

26

6. Республика Дагестан

26

7. Республика Башкортостан

25

8. Республика Татарстан

23

9. Ульяновская область

22

10. Курская область

21

11. Красноярский край

21

12. Рязанская область

17

13. Ставропольский край

14

14. Краснодарский край

13

15. Свердловская область

13

16. Республика Калмыкия

9

17. Ростовская область

9

18. Ямало-Ненецкий АО

9

19. Чеченская Республика

8

20. Тюменская область

8

21. Алтайский край

8

22. Тверская область

7

23. Чувашская Республика

7

24. Новосибирская область

7

25. Владимирская область

6

26. Калужская область

6

27. Кировская область

6

28. Челябинская область

6

29. Орловская область

5

30. Ленинградская область

5

31. Волгоградская область

5

32. Камчатский край

5

33. Смоленская область

4

34. Липецкая область

3

35. Калининградская область

3

36. Кабардино-Балкарская Республика

3

37. Республика Хакасия

3

38. Республика Саха (Якутия)

3

39. Приморский край

3

40. Ивановская область

2

41. Иркутская область

2

42. Амурская область

2

43. Вологодская область

1

44. Самарская область

1

45. Саратовская область

1

46. Республика Бурятия

1

47. Кемеровская область

1

48. Хабаровский край

1

49. г. Севастополь

1

"""

In [136]:
dd = {}
for line in s.split('\n'):
    if line == '':
        pass
    elif len(line) > 5:
        city = ' '.join(line.split(' ')[1:]).strip()
    elif len(line) < 5:
        num = int(line)
        dd[city] = num

In [137]:
dd

{'Москва': 1030,
 'Московская область': 152,
 'Санкт-Петербург': 80,
 'Нижегородская область': 33,
 'Брянская область': 26,
 'Республика Дагестан': 26,
 'Республика Башкортостан': 25,
 'Республика Татарстан': 23,
 'Ульяновская область': 22,
 'Курская область': 21,
 'Красноярский край': 21,
 'Рязанская область': 17,
 'Ставропольский край': 14,
 'Краснодарский край': 13,
 'Свердловская область': 13,
 'Республика Калмыкия': 9,
 'Ростовская область': 9,
 'Ямало-Ненецкий АО': 9,
 'Чеченская Республика': 8,
 'Тюменская область': 8,
 'Алтайский край': 8,
 'Тверская область': 7,
 'Чувашская Республика': 7,
 'Новосибирская область': 7,
 'Владимирская область': 6,
 'Калужская область': 6,
 'Кировская область': 6,
 'Челябинская область': 6,
 'Орловская область': 5,
 'Ленинградская область': 5,
 'Волгоградская область': 5,
 'Камчатский край': 5,
 'Смоленская область': 4,
 'Липецкая область': 3,
 'Калининградская область': 3,
 'Кабардино-Балкарская Республика': 3,
 'Республика Хакасия': 3,
 'Республика Саха (Якутия)': 3,
 'Приморский край': 3,
 'Ивановская область': 2,
 'Иркутская область': 2,
 'Амурская область': 2,
 'Вологодская область': 1,
 'Самарская область': 1,
 'Саратовская область': 1,
 'Республика Бурятия': 1,
 'Кемеровская область': 1,
 'Хабаровский край': 1,
 'г. Севастополь': 1}

In [138]:
daily_data = daily_data.append(dd, ignore_index=True)

In [141]:
daily_data

,Воронежская область,Ивановская область,Кировская область,Краснодарский край,Красноярский край,Москва,Московская область,Мурманская область,Нижегородская область,Новосибирская область,...,Ямало-Ненецкий АО,Еврейская АО,Республика Ингушетия,Камчатский край,Республика Карелия,Чувашская Республика,Карачаево-Черкесская Республика,Забайкальский край,Республика Тыва,г. Севастополь
0,2.0,1.0,2.0,2.0,3.0,12.0,5.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,2.0,NaN,NaN,33.0,1.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,2.0,1.0,6.0,17.0,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,2.0,NaN,NaN,54.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,71.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,NaN,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,4.0,NaN,120.0,6.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,3.0,136.0,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,1.0,1.0,NaN,NaN,157.0,8.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,5.0,NaN,8.0,4.0,114.0,36.0,NaN,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,1.0,NaN,NaN,197.0,27.0,2.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,2.0,3.0,NaN,2.0,212.0,7.0,2.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2.0,NaN,NaN,NaN,NaN,387.0,NaN,6.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,4.0,2.0,NaN,5.0,6.0,267.0,15.0,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,5.0,595.0,43.0,4.0,13.0,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,2.0,3.0,17.0,NaN,448.0,34.0,NaN,NaN,NaN,...,10.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2.0,10.0,3.0,NaN,NaN,434.0,49.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,4.0,536.0,45.0,NaN,22.0,1.0,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
18,9.0,10.0,NaN,11.0,3.0,591.0,82.0,3.0,9.0,NaN,...,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN
19,NaN,14.0,2.0,11.0,NaN,697.0,67.0,NaN,NaN,NaN,...,18.0,NaN,6.0,NaN,NaN,3.0,3.0,NaN,NaN,NaN
20,10.0,NaN,NaN,24.0,7.0,660.0,95.0,25.0,24.0,2.0,...,11.0,3.0,18.0,NaN,NaN,9.0,2.0,3.0,NaN,NaN
21,NaN,13.0,8.0,20.0,NaN,857.0,199.0,1.0,7.0,5.0,...,NaN,NaN,NaN,3.0,NaN,2.0,1.0,NaN,NaN,NaN
22,4.0,NaN,1.0,20.0,NaN,1124.0,182.0,23.0,32.0,3.0,...,NaN,2.0,4.0,NaN,NaN,15.0,3.0,NaN,6.0,NaN
23,NaN,2.0,6.0,13.0,21.0,1030.0,152.0,NaN,33.0,7.0,...,9.0,NaN,NaN,5.0,NaN,7.0,NaN,NaN,NaN,1.0

In [150]:
daily_data['Дата'] = list(urls.keys())

In [152]:
daily_data.to_csv('../Russia_regions_covid_daily_data.csv', index=False)

# 12.04.2020

In [4]:
daily_data = pd.read_csv('../data/Russia_regions_covid_daily_data.csv')

In [14]:
s = """
1. Москва – 1306
2. Московская область – 278
3. Санкт-Петербург – 69
4. Мурманская область – 61
5. Нижегородская область – 42
6. Краснодарский край – 31
7. Красноярский край – 25
8. Владимирская область – 23
9. Республика Мордовия – 23
10. Республика Башкортостан – 19
11. Брянская область – 18
12. Ивановская область – 18
13. Чеченская Республика – 17
14. Рязанская область – 16
15. Тамбовская область – 15
16. Пермский край – 15
17. Ярославская область – 14
18. Ростовская область – 14
19. Воронежская область – 12
20. Ямало-Ненецкий АО – 12
21. Республика Бурятия – 12
22. Чувашская Республика – 11
23. Амурская область – 11
24. Тюменская область – 9
25. Ставропольский край – 8
26. Астраханская область – 8
27. Ульяновская область – 8
28. Республика Северная Осетия – 7
29. Республика Марий Эл – 7
30. Саратовская область – 7
31. Белгородская область – 5
32. Липецкая область – 5
33. Калининградская область – 5
34. Ленинградская область – 5
35. Кабардино-Балкарская Республика – 5
36. Волгоградская область – 5
37. Иркутская область – 5
38. Свердловская область – 4
39. Забайкальский край – 4
40. Костромская область – 3
41. Тульская область – 3
42. Вологодская область – 3
43. Самарская область – 3
44. Республика Саха (Якутия) – 3
45. Карачаево-Черкесская Республика – 2
46. Удмуртская Республика – 2
47. Омская область – 2
48. Республика Крым – 2
49. Курская область – 1
50. Кировская область – 1
51. Курганская область – 1
52. Приморский край – 1"""

In [15]:
dd = get_data1(s)
dd['Дата'] = '12.04.2020'

In [16]:
daily_data = daily_data.append(dd, ignore_index=True)

In [17]:
daily_data.to_csv('../data/Russia_regions_covid_daily_data.csv', index=False)

# 13.04.2020

In [7]:
s = """1. Москва - 1355

2. Московская область - 495

3. Санкт-Петербург - 121

4. Тверская область - 44

5. Краснодарский край - 41

6. Нижегородская область - 30

7. Ростовская область - 26

8. Красноярский край - 25

9. Республика Башкортостан - 23

10. Оренбургская область - 20

11. Рязанская область - 18

12. Пензенская область - 17

13. Ленинградская область - 16

14. Республика Мордовия - 16

15. Ульяновская область - 16

16. Курская область - 15

17. Кабардино-Балкарская Республика - 15

18. Чувашская Республика - 15

19. Кировская область - 15

20. Тюменская область - 14

21. Хабаровский край - 14

22. Владимирская область - 13

23. Ставропольский край - 12

24. Воронежская область - 11

25. Тульская область - 11

26. Республика Татарстан - 11

27. Калужская область - 10

28. Республика Марий Эл - 10

29. Новгородская область - 8

30. Новосибирская область - 8

31. Архангельская область - 7

32. Свердловская область - 7

33. Иркутская область - 7

34. Ивановская область - 6

35. Липецкая область - 6

36. Волгоградская область - 6

37. Забайкальский край - 6

38. Орловская область - 5

39. Псковская область - 5

40. Республика Ингушетия - 5

41. Самарская область - 5

42. Смоленская область - 4

43. Калининградская область - 4

44. Ямало-Ненецкий АО - 4

45. Республика Бурятия - 4

46. Томская область - 4

47. Приморский край - 4

48. Челябинская область - 3

49. Республика Саха (Якутия) - 3

50. Карачаево-Черкесская Республика - 2

51. Чеченская Республика - 2

52. Саратовская область - 2

53. Алтайский край - 2

54. Кемеровская область - 2

55. Брянская область - 1

56. Республика Карелия - 1

57. Вологодская область - 1

58. Астраханская область - 1

59. Омская область - 1

60. Магаданская область - 1

61. Еврейская АО - 1

62. Республика Крым - 1"""

In [1]:
daily_data = pd.read_csv('../data/Russia_regions_covid_daily_data.csv')

In [8]:
dd = get_data4(s)

In [10]:
dd['Дата'] = '13.04.2020'

In [11]:
daily_data = daily_data.append(dd, ignore_index=True)

In [14]:
daily_data.to_csv('../data/Russia_regions_covid_daily_data.csv', index=False)

# 14.04.2020

In [6]:
s = '''
1. Москва - 1489

2. Московская область - 460

3. Санкт-Петербург - 121

4. Республика Коми - 97

5. Нижегородская область - 68

6. Тамбовская область - 35

7. Ленинградская область - 35

8. Смоленская область - 34

9. Рязанская область - 27

10. Пермский край - 27

11. Республика Татарстан - 23

12. Республика Башкортостан - 22

13. Красноярский край - 21

14. Ростовская область - 20

15. Республика Северная Осетия - 18

16. Владимирская область - 16

17. Республика Дагестан - 16

18. Калужская область - 15

19. Чеченская Республика - 15

20. Ханты-Мансийский АО - 15

21. Тюменская область - 14

22. Республика Мордовия - 13

23. Республика Марий Эл - 11

24. Самарская область - 11

25. Белгородская область - 10

26. Ивановская область - 10

27. Ставропольский край - 9

28. Республика Бурятия - 9

29. Воронежская область - 8

30. Оренбургская область - 8

31. Свердловская область - 8

32. Республика Хакасия - 8

33. Орловская область - 7

34. Вологодская область - 7

35. Республика Адыгея - 7

36. Томская область - 7

37. Удмуртская Республика - 6

38. Липецкая область - 5

39. Калининградская область - 5

40. Краснодарский край - 5

41. Саратовская область - 5

42. Челябинская область - 5

43. Алтайский край - 5

44. Иркутская область - 4

45. Приморский край - 4

46. Карачаево-Черкесская Республика - 3

47. Волгоградская область - 2

48. Архангельская область - 1

49. Республика Саха (Якутия) - 1

50. Магаданская область - 1

51. г. Севастополь - 1
'''

In [7]:
daily_data = pd.read_csv('../data/Russia_regions_covid_daily_data.csv')

dd = get_data4(s)

dd['Дата'] = '14.04.2020'

In [9]:
daily_data = daily_data.append(dd, ignore_index=True)
daily_data.to_csv('../data/Russia_regions_covid_daily_data.csv', index=False)